make-node:
	docker-machine create --driver virualbox node1
    docker-machine create --driver virualbox node2
    docker-machine create --driver virualbox node3

ssh-1:
	docker-machine ssh node1

ssh-2:
	docker-machine ssh node2

ssh-3:
	docker-machine ssh node3